const API_URL="COLE_AQUI_O_LINK_DO_APPS_SCRIPT";
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const money=v=>Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const state={token:localStorage.getItem('dge_token')||'',user:null,produtos:[],vendas:[],usuarios:[]};
async function api(acao,dados={}){const r=await fetch(API_URL,{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify({acao,token:state.token,...dados})});const j=await r.json();if(!j.ok)throw new Error(j.erro||'Erro na operação');return j}
function hoje(){return new Date().toISOString().slice(0,10)}
function parseMoney(v){return Number(String(v||'').replace(/R\$/g,'').replace(/\./g,'').replace(',','.').replace(/[^0-9.-]/g,''))||0}
function formObj(f){return Object.fromEntries(new FormData(f).entries())}
function isAdmin(){return state.user?.perfil==='Administrador'}
function showApp(){ $('#login').classList.add('hidden');$('#app').classList.remove('hidden');$('#userInfo').textContent=`${state.user.nome} • ${state.user.perfil}`;$$('.admin-only').forEach(x=>x.classList.toggle('hidden',!isAdmin()));carregarTudo() }
$('#loginForm').onsubmit=async e=>{e.preventDefault();const d=formObj(e.currentTarget);$('#loginMsg').textContent='Entrando...';try{const j=await api('login',d);state.token=j.token;state.user=j.usuario;localStorage.setItem('dge_token',state.token);showApp()}catch(err){$('#loginMsg').textContent=err.message}}
$('#sair').onclick=()=>{localStorage.removeItem('dge_token');location.reload()};$('#menu').onclick=()=>document.querySelector('aside').classList.toggle('open');
$$('.nav').forEach(b=>b.onclick=()=>{if(b.classList.contains('admin-only')&&!isAdmin())return;$$('.nav').forEach(x=>x.classList.remove('active'));b.classList.add('active');$$('.page').forEach(x=>x.classList.remove('active'));$(`#page-${b.dataset.page}`).classList.add('active');$('#titulo').textContent=b.textContent.trim();document.querySelector('aside').classList.remove('open')});
async function carregarTudo(){await Promise.all([carregarDashboard(),carregarProdutos(),carregarVendas(),isAdmin()?carregarUsuarios():Promise.resolve()]);const d=$('#vendaForm [name=dataVenda]');if(d&&!d.value)d.value=hoje()}
async function carregarDashboard(){try{const j=await api('dashboard');$('#fatHoje').textContent=money(j.faturamentoHoje);$('#fatMes').textContent=money(j.faturamentoMes);$('#vendasMes').textContent=j.vendasMes;$('#estoque').textContent=j.estoque;$('#dashVendas').innerHTML=(j.ultimasVendas||[]).map(v=>`<tr><td>${esc(v.data)}</td><td>${esc(v.cliente)}</td><td>${esc(v.produto)}</td><td>${money(v.valor)}</td><td>${esc(v.vendedora)}</td></tr>`).join('')||'<tr><td colspan="5">Nenhuma venda.</td></tr>'}catch(e){console.error(e)}}
async function carregarProdutos(){try{const j=await api('listarProdutos');state.produtos=j.produtos||[];$('#produtoVenda').innerHTML='<option value="">Selecione</option>'+state.produtos.filter(p=>p.status==='Publicado'&&Number(p.quantidade)>0).map(p=>`<option value="${esc(p.id)}" data-preco="${p.preco}">${esc(p.nome)} • ${esc(p.categoria)} • ${money(p.preco)} • estoque ${p.quantidade}</option>`).join('');$('#produtosBody').innerHTML=state.produtos.map(p=>`<tr><td>${p.fotos?.[0]?`<img class="thumb" src="${esc(p.fotos[0])}">`:'Sem foto'}</td><td><strong>${esc(p.nome)}</strong><br><small>${esc(p.descricao||'')}</small></td><td>${esc(p.categoria)}</td><td>${money(p.preco)}</td><td>${p.quantidade}</td><td><span class="pill">${esc(p.status)}</span></td><td><div class="row-actions"><button onclick="editarProduto('${p.id}')">Editar</button>${isAdmin()?`<button onclick="statusProduto('${p.id}','${p.status==='Publicado'?'Oculto':'Publicado'}')">${p.status==='Publicado'?'Ocultar':'Publicar'}</button><button class="danger" onclick="excluirProduto('${p.id}')">Excluir</button>`:''}</div></td></tr>`).join('')||'<tr><td colspan="7">Nenhum produto.</td></tr>'}catch(e){console.error(e)}}
$('#produtoVenda').onchange=e=>{const op=e.target.selectedOptions[0];if(op?.dataset.preco)$('#vendaForm [name=valorVenda]').value=Number(op.dataset.preco).toLocaleString('pt-BR',{minimumFractionDigits:2})}
function alternarTipoVenda(){
  const avulsa=$('#tipoVenda').value==='avulsa';
  $('#campoProdutoEstoque').classList.toggle('hidden',avulsa);
  $('#camposVendaAvulsa').classList.toggle('hidden',!avulsa);
  $('#produtoVenda').required=!avulsa;
  $('#vendaForm [name=produtoManual]').required=avulsa;
  if(avulsa){$('#produtoVenda').value=''}
  else{$('#vendaForm [name=produtoManual]').value='';$('#vendaForm [name=marcaManual]').value='';$('#vendaForm [name=modeloManual]').value='';$('#vendaForm [name=categoriaManual]').value=''}
}
$('#tipoVenda').onchange=alternarTipoVenda;
alternarTipoVenda();

async function carregarVendas(){try{const j=await api('listarVendas');state.vendas=j.vendas||[];$('#vendasBody').innerHTML=state.vendas.map(v=>`<tr><td>${esc(v.data)}</td><td>${esc(v.cliente)}<br><small>${esc(v.documento||'')}</small></td><td>${esc(v.produto)}</td><td>${money(v.valor)}</td><td>${esc(v.pagamento)}</td><td>${esc(v.vendedora)}</td><td><button onclick="imprimirRecibo('${v.id}')">Recibo</button>${isAdmin()?` <button class="danger" onclick="excluirVenda('${v.id}')">Excluir</button>`:''}</td></tr>`).join('')||'<tr><td colspan="7">Nenhuma venda.</td></tr>'}catch(e){console.error(e)}}
$('#recarregarVendas').onclick=carregarVendas;
$('#vendaForm').onsubmit=async e=>{e.preventDefault();const f=e.currentTarget,d=formObj(f);d.valorVenda=parseMoney(d.valorVenda);d.quantidade=Number(d.quantidade||1);const msg=f.querySelector('.msg');msg.textContent='Salvando...';try{const j=await api('cadastrarVenda',d);msg.textContent='Venda salva.';if(d.imprimir)abrirRecibo(j.venda);f.reset();f.dataVenda.value=hoje();f.tipoVenda.value='estoque';alternarTipoVenda();await carregarTudo()}catch(err){msg.textContent=err.message}}
function abrirRecibo(v){const w=open('','_blank','width=850,height=900');w.document.write(`<!doctype html><html><head><meta charset="utf-8"><title>Recibo ${esc(v.id)}</title><style>body{font-family:Arial;padding:45px;color:#111}.top{display:flex;justify-content:space-between;gap:24px;border-bottom:3px solid #f5b400;padding-bottom:18px}.logo{font-size:28px;font-weight:800}.company{margin-top:8px;font-size:12px;line-height:1.55;color:#444}.receipt{text-align:right}.box{border:1px solid #ddd;border-radius:10px;padding:18px;margin-top:22px}.row{display:flex;justify-content:space-between;gap:20px;padding:8px 0;border-bottom:1px solid #eee}.row:last-child{border-bottom:0}.sign{margin-top:70px;text-align:center}.sign div{border-top:1px solid #111;width:360px;margin:auto;padding-top:8px;font-weight:700}.sign small{display:block;margin-top:5px;color:#555}@media print{button{display:none}body{padding:20px}}</style></head><body><div class="top"><div><div class="logo">DG ELETROS</div><div class="company"><b>DG ELETROS LTDA ME</b><br>CNPJ: 60.364.662/0001-72<br>Rua Afonso Vidal, 264 — Vila Andrade<br>São Paulo/SP — CEP 05723-330<br>Telefone: (11) 97971-8211</div></div><div class="receipt"><b>RECIBO DE VENDA</b><br>${esc(v.id)}</div></div><div class="box"><div class="row"><span>Cliente</span><b>${esc(v.cliente)}</b></div><div class="row"><span>CPF/CNPJ</span><b>${esc(v.documento||'Não informado')}</b></div><div class="row"><span>Telefone</span><b>${esc(v.telefone||'Não informado')}</b></div><div class="row"><span>Produto</span><b>${esc(v.produto)}</b></div><div class="row"><span>Quantidade</span><b>${v.quantidade}</b></div><div class="row"><span>Data</span><b>${esc(v.data)}</b></div><div class="row"><span>Pagamento</span><b>${esc(v.pagamento)}</b></div><div class="row"><span>Garantia</span><b>${v.garantia||0} dias</b></div><div class="row"><span>Valor total</span><b>${money(v.valor)}</b></div></div><div class="box"><b>Observações:</b><p>${esc(v.observacoes||'Sem observações.')}</p></div><p>Recebemos do cliente acima identificado o valor referente ao produto descrito neste recibo.</p><div class="sign"><div>DG ELETROS LTDA ME</div><small>CNPJ 60.364.662/0001-72</small></div><button onclick="print()">Imprimir</button><script>setTimeout(()=>print(),400)<\/script></body></html>`);w.document.close()}
window.imprimirRecibo=id=>{const v=state.vendas.find(x=>x.id===id);if(v)abrirRecibo(v)}
window.excluirVenda=async id=>{if(!confirm('Excluir esta venda e devolver a quantidade ao estoque?'))return;const motivo=prompt('Motivo da exclusão:');if(!motivo)return;try{await api('excluirVenda',{id,motivo});await carregarTudo()}catch(e){alert(e.message)}}
function abrirModal(html){$('#modalConteudo').innerHTML=html;$('#modal').classList.remove('hidden')}$('#fecharModal').onclick=()=>$('#modal').classList.add('hidden');$('#modal').onclick=e=>{if(e.target===$('#modal'))$('#modal').classList.add('hidden')}
$('#novoProduto').onclick=()=>formProduto();window.editarProduto=id=>formProduto(state.produtos.find(p=>p.id===id));
function formProduto(p={}){abrirModal(`<h2>${p.id?'Editar':'Novo'} produto</h2><form id="produtoForm" class="grid"><input type="hidden" name="id" value="${esc(p.id||'')}"><label>Nome do produto<input name="nome" required value="${esc(p.nome||'')}"></label><label>Categoria<select name="categoria">${['Geladeira','Lavadora','Fogão','Micro-ondas','TV','Ar-condicionado','Ferramenta','Portátil','Eletrônico','Outro'].map(x=>`<option ${p.categoria===x?'selected':''}>${x}</option>`).join('')}</select></label><label>Marca<input name="marca" value="${esc(p.marca||'')}"></label><label>Modelo<input name="modelo" value="${esc(p.modelo||'')}"></label><label>Classificação<select name="classificacao"><option ${p.classificacao==='A'?'selected':''}>A</option><option ${p.classificacao==='B'?'selected':''}>B</option></select></label><label>Preço no PIX<input name="preco" required value="${p.preco?Number(p.preco).toLocaleString('pt-BR',{minimumFractionDigits:2}):''}"></label><label>Quantidade<input type="number" name="quantidade" min="0" required value="${p.quantidade??1}"></label><label>Status<select name="status">${['Publicado','Oculto','Reservado'].map(x=>`<option ${p.status===x?'selected':''}>${x}</option>`).join('')}</select></label><label class="full">Descrição<textarea name="descricao" rows="3">${esc(p.descricao||'')}</textarea></label><label class="full">Fotos do produto<input type="file" name="fotos" accept="image/*" multiple><small>Até 6 fotos. Ao editar, novas fotos substituem as atuais.</small></label><div class="full preview">${(p.fotos||[]).map(x=>`<img src="${esc(x)}">`).join('')}</div><div class="full actions"><button class="primary">Salvar produto</button><span class="msg"></span></div></form>`);$('#produtoForm').onsubmit=salvarProduto}
async function fileData(file){const data=await new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>res(r.result);r.onerror=rej;r.readAsDataURL(file)});return {nome:file.name,data}}
async function salvarProduto(e){e.preventDefault();const f=e.currentTarget,d=formObj(f);d.preco=parseMoney(d.preco);d.quantidade=Number(d.quantidade||0);const files=[...f.fotos.files];if(files.length>6)return alert('Selecione no máximo 6 fotos.');if(files.length){d.fotos=[];for(const file of files)d.fotos.push(await fileData(file))}delete d.fotos;d.fotosUpload=[];for(const file of files)d.fotosUpload.push(await fileData(file));const msg=f.querySelector('.msg');msg.textContent='Salvando...';try{await api('salvarProduto',d);$('#modal').classList.add('hidden');await carregarTudo()}catch(err){msg.textContent=err.message}}
window.statusProduto=async(id,status)=>{try{await api('alterarStatusProduto',{id,status});await carregarProdutos()}catch(e){alert(e.message)}}
window.excluirProduto=async id=>{if(!confirm('Excluir definitivamente este produto?'))return;const motivo=prompt('Motivo da exclusão:');if(!motivo)return;try{await api('excluirProduto',{id,motivo});await carregarTudo()}catch(e){alert(e.message)}}
async function carregarUsuarios(){try{const j=await api('listarUsuarios');state.usuarios=j.usuarios||[];$('#usuariosBody').innerHTML=state.usuarios.map(u=>`<tr><td>${esc(u.nome)}</td><td>${esc(u.usuario)}</td><td>${esc(u.perfil)}</td><td>${esc(u.status)}</td><td><button onclick="editarUsuario('${u.id}')">Editar</button></td></tr>`).join('')}catch(e){console.error(e)}}
$('#novoUsuario').onclick=()=>formUsuario();window.editarUsuario=id=>formUsuario(state.usuarios.find(u=>u.id===id));
function formUsuario(u={}){abrirModal(`<h2>${u.id?'Editar':'Novo'} funcionário</h2><form id="usuarioForm" class="grid"><input type="hidden" name="id" value="${esc(u.id||'')}"><label>Nome<input name="nome" required value="${esc(u.nome||'')}"></label><label>Usuário<input name="usuario" required value="${esc(u.usuario||'')}"></label><label>Senha<input name="senha" type="password" ${u.id?'':'required'} placeholder="${u.id?'Deixe em branco para manter':''}"></label><label>Perfil<select name="perfil"><option ${u.perfil==='Vendedora'?'selected':''}>Vendedora</option><option ${u.perfil==='Administrador'?'selected':''}>Administrador</option></select></label><label>Status<select name="status"><option ${u.status!=='Inativo'?'selected':''}>Ativo</option><option ${u.status==='Inativo'?'selected':''}>Inativo</option></select></label><div class="full"><button class="primary">Salvar</button></div></form>`);$('#usuarioForm').onsubmit=async e=>{e.preventDefault();try{await api('salvarUsuario',formObj(e.currentTarget));$('#modal').classList.add('hidden');carregarUsuarios()}catch(err){alert(err.message)}}}
(async()=>{if(!state.token)return;try{const j=await api('verificarToken');state.user=j.usuario;showApp()}catch(e){localStorage.removeItem('dge_token')}})();
