const crypto=require('node:crypto');
const {records,one,save,remove,query}=require('./db');
const n=v=>{if(typeof v==='number')return Number.isFinite(v)?v:0;let s=String(v??'').replace(/R\$/g,'').trim();if(s.includes(',')&&s.includes('.'))s=s.replace(/\./g,'').replace(',','.');else if(s.includes(','))s=s.replace(',','.');return Number(s.replace(/[^\d.-]/g,''))||0};
const id=p=>`${p}-${crypto.randomUUID()}`;
const hash=s=>crypto.createHash('sha256').update(String(s)).digest('base64');
const date=()=>new Date().toISOString().slice(0,10);
const iso=v=>{const s=String(v||'');if(/^\d{4}-\d{2}-\d{2}/.test(s))return s.slice(0,10);const m=s.match(/^(\d{2})\/(\d{2})\/(\d{4})/);return m?`${m[3]}-${m[2]}-${m[1]}`:s.slice(0,10)};
const fmt=v=>{const d=iso(v);return /^\d{4}-\d{2}-\d{2}$/.test(d)?`${d.slice(8)}/${d.slice(5,7)}/${d.slice(0,4)}`:String(v||'')};
const parseJSON=v=>{try{const x=JSON.parse(v||'[]');return Array.isArray(x)?x:[]}catch{return []}};
const yes=v=>['sim','true','1'].includes(String(v||'').toLowerCase());
const heavy=c=>['geladeira','lavadora','fogao','micro ondas','microondas','ar condicionado','frigobar','maquina de lavar','lava e seca','freezer'].some(x=>String(c||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().includes(x));
const resale=(p,c)=>Math.round(n(p)*(heavy(c)?.89:.82)*100)/100;
function photos(p){let a=parseJSON(p.Fotos);if(!a.length && p['Link da Imagem'])a=[p['Link da Imagem']];return a.filter(Boolean)}
function product(p){const preco=n(p['Preço']);return {id:p.ID||p._key,linha:p._linha,versao:hash(JSON.stringify(p)),nome:p.Produto||'',categoria:p.Categoria||'outros',preco,precoCusto:n(p['Preço de custo']),precoRevenda:resale(preco,p.Categoria),classificacao:p['Classificação']||'',descricao:p['Descrição']||'',comentarioRevendedor:p['Comentário revendedor']||'',marca:p.Marca||'',modelo:p.Modelo||'',quantidade:p.Quantidade==null||p.Quantidade===''?1:Math.max(0,n(p.Quantidade)),status:p.Status||'Publicado',promocao:p['Promoção']||'Não',whatsapp:p.WhatsApp||'',fotos:photos(p)}}
function sale(x){const valor=n(x['Valor da venda']),quantidade=n(x.Quantidade),custoUnitario=n(x['Custo unitário']),custoTotal=x['Custo total']==null?custoUnitario*quantidade:n(x['Custo total']),parcelas=parseJSON(x['Parcelas JSON']),recebimentos=parseJSON(x['Recebimentos JSON']);return {id:x['ID Venda'],data:fmt(x['Data da venda']),cliente:x.Cliente,documento:x['CPF/CNPJ'],telefone:x.Telefone,idProduto:x['ID Produto'],produto:x.Produto,quantidade,valor,custoUnitario,custoTotal,lucro:x.Lucro==null?valor-custoTotal:n(x.Lucro),pagamento:x['Forma de pagamento'],garantia:n(x['Garantia dias']),observacoes:x['Observações'],vendedora:x.Vendedora,origem:x['Origem do produto'],entrada:n(x.Entrada),saldo:n(x['Saldo a receber']),parcelas,totalParcelas:parcelas.length,parcelasPagas:parcelas.filter(p=>p.status==='Pago').length,statusRecebimento:x['Status recebimento'],recebimentos,statusComissao:x['Status comissão']||'Pendente',comissaoRevisadaPor:x['Comissão revisada por'],dataRevisaoComissao:fmt(x['Data revisão comissão'])}};
const role=(u,...roles)=>{if(!roles.includes(u.Perfil))throw new Error('Sem permissão para esta operação.')};
async function log(u,type,key,reason){const k=id('LOG');await save('LogExclusoes',k,{Data:new Date().toISOString(),Tipo:type,ID:key,Motivo:reason||'',Usuário:u.Nome})}
async function storePhotos(upload){const urls=[];for(const f of upload.slice(0,6)){const match=String(f.data||'').match(/^data:(image\/(?:jpeg|png|webp));base64,([\s\S]+)$/);if(!match)throw new Error('Foto inválida. Use JPG, PNG ou WebP.');const bytes=Buffer.from(match[2],'base64');if(bytes.length>500000)throw new Error('Cada foto deve ter no máximo 500 KB.');const magic=match[1]==='image/jpeg'?bytes.subarray(0,3).toString('hex')==='ffd8ff':match[1]==='image/png'?bytes.subarray(0,8).toString('hex')==='89504e470d0a1a0a':bytes.subarray(0,4).toString()==='RIFF'&&bytes.subarray(8,12).toString()==='WEBP';if(!magic)throw new Error('Formato de imagem inválido.');const photo=id('IMG');await query('INSERT INTO dge_photos(photo_id,mime_type,content) VALUES($1,$2,decode($3,\'base64\'))',[photo,match[1],match[2]]);urls.push('/api/foto?id='+encodeURIComponent(photo))}return urls}
module.exports={n,id,hash,date,iso,fmt,parseJSON,yes,heavy,resale,photos,product,sale,role,log,storePhotos,records,one,save,remove,query};
