// Execução única, depois da importação SQL. Requer DATABASE_URL no ambiente local.
// Apenas imagens públicas do Drive podem ser copiadas. Links privados são listados ao final.
const crypto=require('node:crypto');
const {records,query}=require('../lib/db');
const allowed=/^https:\/\/(?:drive\.google\.com|[\w.-]*\.googleusercontent\.com)\//i;
function imageType(bytes){if(bytes.subarray(0,3).toString('hex')==='ffd8ff')return 'image/jpeg';if(bytes.subarray(0,8).toString('hex')==='89504e470d0a1a0a')return 'image/png';if(bytes.subarray(0,4).toString()==='RIFF'&&bytes.subarray(8,12).toString()==='WEBP')return 'image/webp';return null}
async function run(){let ok=0,failed=[];const products=await records('Produtos');for(const p of products){let photos=[];try{photos=JSON.parse(p.Fotos||'[]')}catch{}if(!Array.isArray(photos))photos=[];if(!photos.length&&p['Link da Imagem'])photos=[p['Link da Imagem']];let changed=false;for(let i=0;i<photos.length;i++){const url=photos[i];if(typeof url!=='string'||url.startsWith('/api/foto'))continue;if(!allowed.test(url)){failed.push({id:p.ID||p._key,index:i+1,reason:'link externo ou inválido'});continue}try{const response=await fetch(url,{redirect:'follow',signal:AbortSignal.timeout(20000)});const bytes=Buffer.from(await response.arrayBuffer()),mime=imageType(bytes);if(!response.ok||!mime||bytes.length>3500000)throw new Error('imagem privada, inválida ou acima de 3,5 MB');const key='IMG-'+crypto.randomUUID();await query('INSERT INTO dge_photos(photo_id,mime_type,content) VALUES($1,$2,decode($3,\'base64\'))',[key,mime,bytes.toString('base64')]);photos[i]='/api/foto?id='+key;ok++;changed=true}catch(e){failed.push({id:p.ID||p._key,index:i+1,reason:e.message})}}if(changed){const data={...p,Fotos:JSON.stringify(photos),'Link da Imagem':photos[0]||''};delete data._key;delete data._linha;await query('UPDATE dge_records SET data=$2::jsonb WHERE collection=\'Produtos\' AND record_key=$1',[p._key,JSON.stringify(data)])}}
  console.log(`${ok} fotos copiadas para o Neon.`);console.log(`${failed.length} imagens pendentes:`);for(const x of failed)console.log(JSON.stringify(x));if(failed.length)process.exitCode=1
}
run().catch(e=>{console.error(e);process.exitCode=1});
