const crypto=require('node:crypto');
const M=require('../lib/model');
const {n,id,hash,date,iso,fmt,parseJSON,yes,resale,product,sale,role,log,storePhotos,records,one,save,remove,query}=M;
const user=u=>({id:u.ID,nome:u.Nome,usuario:u['Usuário'],perfil:u.Perfil});
const cookie=req=>String(req.headers.cookie||'').split(';').map(x=>x.trim()).find(x=>x.startsWith('dge_session='))?.slice(12)||'';
const digest=s=>crypto.createHash('sha256').update(s).digest('hex');
const cookieOptions='Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=28800';
async function authenticate(req){const raw=cookie(req);if(!raw)throw new Error('Sessão expirada.');const rows=await query('SELECT user_key FROM dge_sessions WHERE token_hash=$1 AND expires_at>now()',[digest(raw)]);if(!rows.length)throw new Error('Sessão expirada.');const u=await one('Usuarios',rows[0].user_key);if(!u||u.Status!=='Ativo')throw new Error('Sessão expirada.');return u}
async function products(){return (await records('Produtos')).map(product).filter(x=>x.nome)}
async function sales(){return (await records('Vendas')).reverse().map(sale)}
const cents=x=>Math.round(n(x)*100)/100;
async function action(a,d,u){
  if(u.Perfil==='Revendedor'&&!['verificarToken','listarCatalogoRevendedor'].includes(a))throw new Error('Sem permissão para esta operação.');
  switch(a){
    case 'verificarToken':return {ok:true,usuario:user(u)};
    case 'listarProdutos':return {ok:true,produtos:await products()};
    case 'listarCatalogoRevendedor':{
      role(u,'Administrador','Revendedor');const p=(await products()).filter(x=>x.status==='Publicado'&&x.quantidade>0&&x.preco>0).map(x=>({id:x.id,nome:x.nome,categoria:x.categoria,marca:x.marca,modelo:x.modelo,descricao:x.descricao,classificacao:x.classificacao,comentarioRevendedor:x.comentarioRevendedor,fotos:x.fotos,quantidade:x.quantidade,precoNormal:x.preco,precoRevenda:resale(x.preco,x.categoria),descontoPercentual:M.heavy(x.categoria)?11:18}));return {ok:true,produtos:p};
    }
    case 'salvarProduto':{
      role(u,'Administrador','Vendedor','Vendedora');const p=await one('Produtos',d.id,d.linha);const key=p? p._key:id('PROD');const photos=Array.isArray(d.fotosUpload)&&d.fotosUpload.length?await storePhotos(d.fotosUpload):p?M.photos(p):[];if(!String(d.nome||'').trim())throw new Error('Informe o nome do produto.');const data={...(p||{}),Produto:String(d.nome).trim(),Categoria:d.categoria||'', 'Preço':cents(d.preco),'Preço de custo':cents(d.precoCusto),'Classificação':d.classificacao||'A','Descrição':d.descricao||'','Comentário revendedor':d.comentarioRevendedor||'', 'Link da Imagem':photos[0]||'','Promoção':d.promocao||p?.['Promoção']||'Não',ID:key,Marca:d.marca||'',Modelo:d.modelo||'',Quantidade:Math.max(0,n(d.quantidade)),Status:d.status||'Publicado',Fotos:JSON.stringify(photos),'Data de cadastro':p?.['Data de cadastro']||new Date().toISOString()};delete data._key;delete data._linha;const linha=await save('Produtos',key,data,p?._linha);return {ok:true,id:key,linha};
    }
    case 'alterarStatusProduto':case 'alterarPromocaoProduto':{
      role(u,'Administrador','Vendedor','Vendedora');const p=await one('Produtos',d.id,d.linha);if(!p)throw new Error('Produto não encontrado.');if(a==='alterarStatusProduto'){if(!['Publicado','Oculto','Reservado'].includes(d.status))throw new Error('Status inválido.');p.Status=d.status}else p['Promoção']=yes(d.promocao)?'Sim':'Não';await save('Produtos',p._key,p,p._linha);return {ok:true,status:p.Status,promocao:p['Promoção'],linha:p._linha,id:p._key};
    }
    case 'excluirProduto':{
      role(u,'Administrador','Vendedor','Vendedora');const p=await one('Produtos',d.id,d.linha);if(!p)throw new Error('Produto não encontrado.');await remove('Produtos',p._key);await log(u,'Produto',p._key,d.motivo);return {ok:true};
    }
    case 'listarVendas':return {ok:true,vendas:await sales()};
    case 'listarComissoes':{
      const now=date(),month=now.slice(0,7),all=await sales();let itens=all.filter(v=>u.Perfil==='Administrador'||String(v.vendedora||'').toLowerCase()===String(u.Nome||'').toLowerCase()).map(v=>{const gerada=cents(v.valor*.02),status=['Aprovada','Recusada'].includes(v.statusComissao)?v.statusComissao:'Pendente';return {...v,recebido:cents(v.valor-v.saldo),pendente:v.saldo,statusComissao:status,comissaoGerada:gerada,comissaoTotal:gerada,comissaoPendente:status==='Pendente'?gerada:0,comissaoRecusada:status==='Recusada'?gerada:0}});
      let pagamentos=(await records('Pagamentos Comissoes')).map(x=>({id:x.ID,data:fmt(x['Data do pagamento']),dataIso:iso(x['Data do pagamento']),vendedora:x.Vendedora,valor:n(x['Valor pago']),referencia:x['Referência']||'',registradoPor:x['Registrado por']||''})).filter(p=>u.Perfil==='Administrador'||String(p.vendedora||'').toLowerCase()===String(u.Nome||'').toLowerCase());
      const remaining={};pagamentos.forEach(p=>{const k=String(p.vendedora||'').toLowerCase();remaining[k]=(remaining[k]||0)+p.valor});
      itens.sort((a,b)=>iso(a.data).localeCompare(iso(b.data))).forEach(v=>{const k=String(v.vendedora||'').toLowerCase(),available=v.statusComissao==='Aprovada'?v.comissaoGerada:0,paid=Math.min(available,remaining[k]||0);remaining[k]=Math.max(0,(remaining[k]||0)-paid);v.comissaoPaga=cents(paid);v.comissaoLiberada=cents(available-paid)});
      const sum=(arr,k)=>cents(arr.reduce((s,x)=>s+n(x[k]),0));const vendors={};itens.forEach(v=>{const k=v.vendedora||'Sem vendedor';vendors[k]||={vendedora:k,gerada:0,liberada:0,pendente:0,paga:0};vendors[k].gerada+=v.statusComissao==='Aprovada'?v.comissaoGerada:0;vendors[k].liberada+=v.comissaoLiberada;vendors[k].pendente+=v.comissaoPendente});pagamentos.forEach(p=>{const k=p.vendedora||'Sem vendedor';vendors[k]||={vendedora:k,gerada:0,liberada:0,pendente:0,paga:0};vendors[k].paga+=p.valor});const resumoVendedores=Object.values(vendors).map(v=>({...v,saldoPagar:cents(Math.max(0,v.liberada))})).filter(v=>v.saldoPagar>.009);const saldoPagar=sum(itens,'comissaoLiberada');itens.sort((a,b)=>iso(b.data).localeCompare(iso(a.data)));pagamentos.sort((a,b)=>b.dataIso.localeCompare(a.dataIso));return {ok:true,percentual:2,totalHoje:sum(itens.filter(v=>iso(v.data)===now),'comissaoLiberada'),totalMes:sum(itens.filter(v=>iso(v.data).startsWith(month)),'comissaoLiberada'),totalLiberado:saldoPagar,totalGerado:sum(itens,'comissaoGerada'),totalPendente:sum(itens,'comissaoPendente'),totalPago:sum(pagamentos,'valor'),saldoPagar,vendasMes:itens.filter(v=>iso(v.data).startsWith(month)).length,itens,pagamentos,resumoVendedores};
    }
    case 'alterarStatusComissao':{
      role(u,'Administrador');if(!['Aprovada','Recusada','Pendente'].includes(d.status))throw new Error('Status inválido.');const v=await one('Vendas',d.vendaId);if(!v)throw new Error('Venda não encontrada.');v['Status comissão']=d.status;v['Comissão revisada por']=u.Nome;v['Data revisão comissão']=new Date().toISOString();await save('Vendas',v._key,v,v._linha);return {ok:true,status:d.status};
    }
    case 'registrarPagamentoComissao':{
      role(u,'Administrador');const val=cents(d.valor),name=String(d.vendedora||'').trim();if(!name||val<=0)throw new Error('Informe vendedora e valor.');const summary=await action('listarComissoes',{},u),available=summary.resumoVendedores.find(x=>x.vendedora.toLowerCase()===name.toLowerCase())?.saldoPagar||0;if(val>available+.01)throw new Error('O valor é maior que a comissão disponível.');const key=id('COM');await save('Pagamentos Comissoes',key,{ID:key,'Data do pagamento':new Date().toISOString(),Vendedora:name,'Valor pago':val,'Referência':d.referencia||'Pagamento de comissão','Registrado por':u.Nome});return {ok:true};
    }
    case 'cadastrarVenda':{
      const avulsa=d.tipoVenda==='avulsa',q=Math.max(1,Math.floor(n(d.quantidade)));let p=null,pn=null;
      if(!avulsa){p=await one('Produtos',d.idProduto,d.linhaProduto);if(!p)throw new Error('Produto não encontrado no estoque.');pn=product(p);if(pn.quantidade<q)throw new Error('Quantidade insuficiente no estoque.')}else if(!String(d.produtoManual||'').trim())throw new Error('Informe o produto vendido.');
      const valor=cents(d.valorVenda),entrada=cents(d.entrada),cliente=String(d.cliente||'').trim();if(!cliente||valor<=0||entrada<0||entrada>valor)throw new Error('Confira cliente, valor e entrada da venda.');
      const telefone=String(d.telefone||'').replace(/\D/g,''),documento=String(d.documento||'').replace(/\D/g,'');if(telefone&&!/^\d{10,11}$/.test(telefone))throw new Error('Telefone inválido.');if(documento&&!/^\d{11}$|^\d{14}$/.test(documento))throw new Error('Documento inválido.');
      const key=id('VEN'),custo=pn?.precoCusto||0,produto=pn?pn.nome:[d.produtoManual,d.marcaManual,d.modeloManual].filter(Boolean).join(' • '),saldo=cents(valor-entrada);
      const obj={'ID Venda':key,'Data da venda':iso(d.dataVenda||date()),'Data de cadastro':new Date().toISOString(),Cliente:cliente,'CPF/CNPJ':documento,Telefone:telefone,'ID Produto':pn?.id||'',Produto:produto,Quantidade:q,'Valor da venda':valor,'Custo unitário':custo,'Custo total':cents(custo*q),Lucro:cents(valor-custo*q),'Forma de pagamento':d.pagamento||'','Garantia dias':n(d.garantia),'Observações':d.observacoes||'',Vendedora:u.Nome,'Origem do produto':avulsa?'Venda avulsa':'Estoque',Marca:pn?.marca||d.marcaManual||'',Modelo:pn?.modelo||d.modeloManual||'',Categoria:pn?.categoria||d.categoriaManual||'',Entrada:entrada,'Saldo a receber':saldo,'Parcelas JSON':'[]','Status recebimento':saldo>0?'Pendente':'Pago','Recebimentos JSON':'[]','Status comissão':'Pendente'};
      // Uma consulta atômica reserva o estoque e cadastra a venda; se não houver saldo, nada é gravado.
      if(p){const rows=await query(`WITH reserve AS (UPDATE dge_records SET data=jsonb_set(jsonb_set(data,'{Quantidade}',to_jsonb((data->>'Quantidade')::numeric-$3::numeric),true),'{Status}',to_jsonb(CASE WHEN (data->>'Quantidade')::numeric-$3::numeric<=0 THEN 'Oculto' ELSE COALESCE(data->>'Status','Publicado') END),true) WHERE collection='Produtos' AND record_key=$1 AND COALESCE(NULLIF(data->>'Quantidade','')::numeric,1)>=$3 RETURNING record_key), sale AS (INSERT INTO dge_records(collection,record_key,source_row,data) SELECT 'Vendas',$4,nextval('dge_row_seq'),$5::jsonb FROM reserve RETURNING record_key) SELECT record_key FROM sale`,[p._key,null,q,key,JSON.stringify(obj)]);if(!rows.length)throw new Error('Estoque insuficiente. Atualize a página.')}else await save('Vendas',key,obj);
      return {ok:true,venda:sale(obj)};
    }
    case 'excluirVenda':{
      role(u,'Administrador');const v=await one('Vendas',d.id);if(!v)throw new Error('Venda não encontrada.');const p=v['ID Produto']?await one('Produtos',v['ID Produto']):null;
      if(p){await query(`WITH deleted AS (DELETE FROM dge_records WHERE collection='Vendas' AND record_key=$1 RETURNING data) UPDATE dge_records SET data=jsonb_set(data,'{Quantidade}',to_jsonb(COALESCE(NULLIF(data->>'Quantidade','')::numeric,1)+$3::numeric),true) WHERE collection='Produtos' AND record_key=$2 AND EXISTS (SELECT 1 FROM deleted)`,[v._key,p._key,n(v.Quantidade)])}else await remove('Vendas',v._key);
      await log(u,'Venda',v._key,d.motivo);return {ok:true};
    }
    case 'dashboard':{
      const vs=await sales(),today=date(),month=today.slice(0,7),h=vs.filter(v=>iso(v.data)===today),m=vs.filter(v=>iso(v.data).startsWith(month)),sum=(a,k)=>a.reduce((s,v)=>s+n(v[k]),0),faturamentoHoje=sum(h,'valor'),faturamentoMes=sum(m,'valor'),custoHoje=sum(h,'custoTotal'),custoMes=sum(m,'custoTotal');return {ok:true,faturamentoHoje,faturamentoMes,custoHoje,custoMes,lucroHoje:faturamentoHoje-custoHoje,lucroMes:faturamentoMes-custoMes,totalReceber:sum(vs,'saldo'),vendasMes:m.length,estoque:sum(await products(),'quantidade'),ultimasVendas:vs.slice(0,8)};
    }
    case 'listarContasReceber':{
      const vs=(await sales()).filter(v=>v.saldo>0.009),contas=vs.map(v=>{const recebimentos=v.recebimentos||[],ds=recebimentos.map(r=>iso(r.data)).filter(Boolean).sort(),last=ds.at(-1)||(v.entrada>0?iso(v.data):''),diasSemPagamento=last?Math.max(0,Math.floor((Date.now()-new Date(last+'T00:00:00Z').getTime())/86400000)):0;return {vendaId:v.id,cliente:v.cliente,documento:v.documento,telefone:v.telefone,produto:v.produto,valorVenda:v.valor,entrada:v.entrada,saldo:v.saldo,totalPago:cents(v.valor-v.saldo),quantidadePagamentos:recebimentos.length+(v.entrada>0?1:0),dataVenda:v.data,ultimoPagamento:last?fmt(last):'',diasSemPagamento,vendedora:v.vendedora,status:v.statusRecebimento,recebimentos}});contas.sort((a,b)=>b.diasSemPagamento-a.diasSemPagamento);return {ok:true,contas,totalReceber:cents(contas.reduce((s,c)=>s+c.saldo,0)),clientesPendentes:contas.length};
    }
    case 'registrarRecebimento':{
      const v=await one('Vendas',d.vendaId);if(!v)throw new Error('Venda não encontrada.');const amount=cents(d.valor);if(amount<=0)throw new Error('Valor inválido.');const rec={id:id('REC'),data:iso(d.dataPagamento||date()),valor:amount,observacao:String(d.observacao||''),registradoPor:u.Nome};
      const rows=await query(`UPDATE dge_records SET data=jsonb_set(jsonb_set(jsonb_set(data,'{Recebimentos JSON}',to_jsonb((COALESCE(NULLIF(data->>'Recebimentos JSON',''),'[]')::jsonb || $3::jsonb)::text),true),'{Saldo a receber}',to_jsonb(ROUND((data->>'Saldo a receber')::numeric-$2::numeric,2)),true),'{Status recebimento}',to_jsonb(CASE WHEN (data->>'Saldo a receber')::numeric-$2::numeric>0 THEN 'Pendente' ELSE 'Pago' END),true) WHERE collection='Vendas' AND record_key=$1 AND (data->>'Saldo a receber')::numeric >= $2::numeric RETURNING data`,[v._key,amount,JSON.stringify([rec])]);if(!rows.length)throw new Error('Pagamento maior que o saldo. Atualize a página.');return {ok:true,saldo:n(rows[0].data['Saldo a receber']),recebimentos:parseJSON(rows[0].data['Recebimentos JSON'])};
    }
    case 'alterarStatusParcela':case 'baixarParcela':{
      const v=await one('Vendas',d.vendaId);if(!v)throw new Error('Venda não encontrada.');const ps=parseJSON(v['Parcelas JSON']);const i=a==='baixarParcela'?ps.findIndex((p,j)=>n(p.numero||j+1)===n(d.numero)):n(d.indice);if(i<0||i>=ps.length)throw new Error('Parcela não encontrada.');const paid=a==='baixarParcela'||d.paga===true||String(d.paga)==='true';ps[i].status=paid?'Pago':'Pendente';ps[i].dataPagamento=paid?iso(d.dataPagamento||date()):'';const saldo=cents(ps.filter(p=>p.status!=='Pago').reduce((s,p)=>s+n(p.valor),0));v['Parcelas JSON']=JSON.stringify(ps);v['Saldo a receber']=saldo;v['Status recebimento']=saldo?'Pendente':'Pago';await save('Vendas',v._key,v,v._linha);return {ok:true,saldo};
    }
    case 'listarUsuarios':{
      role(u,'Administrador');return {ok:true,usuarios:(await records('Usuarios')).map(x=>({id:x.ID,nome:x.Nome,usuario:x['Usuário'],perfil:x.Perfil,status:x.Status,salario:n(x['Salário mensal']),horasSemanais:n(x['Horas semanais'])}))};
    }
    case 'salvarUsuario':{
      role(u,'Administrador');const old=d.id?await one('Usuarios',d.id):null,all=await records('Usuarios');if(all.some(x=>String(x['Usuário']).toLowerCase()===String(d.usuario).toLowerCase()&&x.ID!==d.id))throw new Error('Usuário já existe.');if(!String(d.nome||'').trim()||!String(d.usuario||'').trim()||(!old&&!d.senha))throw new Error('Preencha nome, usuário e senha.');if(['Vendedora','Vendedor'].includes(d.perfil)&&(n(d.salario)<=0||n(d.horasSemanais)<=0))throw new Error('Informe salário e carga horária.');const key=old?.ID||id('USR'),obj={ID:key,Nome:d.nome,'Usuário':d.usuario,'Senha Hash':d.senha?hash(d.senha):old['Senha Hash'],Perfil:d.perfil||'Vendedora',Status:d.status||'Ativo','Data de cadastro':old?.['Data de cadastro']||new Date().toISOString(),'Salário mensal':n(d.salario),'Horas semanais':n(d.horasSemanais)};await save('Usuarios',key,obj,old?._linha);return {ok:true};
    }
    case 'excluirUsuario':{
      role(u,'Administrador');if(String(d.id)===u.ID)throw new Error('Não exclua seu próprio usuário.');await remove('Usuarios',String(d.id));return {ok:true};
    }
    case 'registrarHoraExtra':{
      const salario=n(u['Salário mensal']),hs=n(u['Horas semanais']),minutes=Math.floor(n(d.horas))*60+Math.floor(n(d.minutos));if(salario<=0||hs<=0)throw new Error('Cadastre salário e carga horária primeiro.');if(minutes<=0||minutes>1440||n(d.minutos)>59||!String(d.motivo||'').trim()||iso(d.data||date())>date())throw new Error('Confira data, duração e motivo.');const key=id('HEX'),hour=salario/(hs*5),total=cents(hour*minutes/60),obj={ID:key,Data:iso(d.data||date()),'ID Funcionário':u.ID,Funcionário:u.Nome,Minutos:minutes,Motivo:d.motivo,'Salário base':salario,'Horas semanais':hs,'Divisor mensal':hs*5,'Valor hora':hour,'Valor total':total,Status:'Pendente','Data de cadastro':new Date().toISOString()};await save('Horas Extras',key,obj);return {ok:true,registro:{id:key,data:fmt(obj.Data),idFuncionario:u.ID,funcionario:u.Nome,minutos:minutes,motivo:d.motivo,valorHora:hour,valorTotal:total,status:'Pendente'}};
    }
    case 'listarHorasExtras':{
      const all=await records('Horas Extras'),a=all.filter(x=>u.Perfil==='Administrador'||x['ID Funcionário']===u.ID).reverse().map(x=>({id:x.ID,data:fmt(x.Data),dataIso:iso(x.Data),idFuncionario:x['ID Funcionário'],funcionario:x.Funcionário,minutos:n(x.Minutos),motivo:x.Motivo,salarioBase:n(x['Salário base']),horasSemanais:n(x['Horas semanais']),divisorMensal:n(x['Divisor mensal']),valorHora:n(x['Valor hora']),valorTotal:n(x['Valor total']),status:x.Status||'Pendente'})),p=a.filter(x=>x.status!=='Pago'),paid=a.filter(x=>x.status==='Pago'),sum=(a,k)=>a.reduce((s,x)=>s+n(x[k]),0);return {ok:true,registros:a,minutosPendentes:sum(p,'minutos'),valorPendente:sum(p,'valorTotal'),minutosPagos:sum(paid,'minutos'),valorPago:sum(paid,'valorTotal'),valorTotal:sum(a,'valorTotal')};
    }
    case 'alterarStatusHoraExtra':case 'excluirHoraExtra':{
      const x=await one('Horas Extras',d.id);if(!x)throw new Error('Lançamento não encontrado.');if(a==='alterarStatusHoraExtra'){role(u,'Administrador');x.Status=d.status==='Pago'?'Pago':'Pendente';await save('Horas Extras',x._key,x,x._linha);return {ok:true,status:x.Status}}if(u.Perfil!=='Administrador'&&(x['ID Funcionário']!==u.ID||x.Status==='Pago'))throw new Error('Sem permissão.');await remove('Horas Extras',x._key);return {ok:true};
    }
    default:throw new Error('Ação não implementada: '+a);
  }
}
module.exports=async function handler(req,res){res.setHeader('Cache-Control','no-store');res.setHeader('X-Content-Type-Options','nosniff');if(req.method!=='POST')return res.status(405).json({ok:false,erro:'Método inválido.'});try{if(Buffer.byteLength(JSON.stringify(req.body||{}))>4000000)throw new Error('Envio muito grande. Reduza as fotos.');const d=req.body||{};if(d.acao==='login'){const all=await records('Usuarios'),u=all.find(x=>String(x['Usuário']).toLowerCase()===String(d.usuario||'').toLowerCase()&&x['Senha Hash']===hash(d.senha||'')&&x.Status==='Ativo');if(!u)throw new Error('Usuário ou senha inválidos.');const raw=crypto.randomBytes(32).toString('hex');await query('INSERT INTO dge_sessions(token_hash,user_key,expires_at) VALUES($1,$2,now()+interval \'8 hours\')',[digest(raw),u._key]);res.setHeader('Set-Cookie','dge_session='+raw+'; '+cookieOptions);return res.json({ok:true,token:'session',usuario:user(u)})}if(d.acao==='sair'){const raw=cookie(req);if(raw)await query('DELETE FROM dge_sessions WHERE token_hash=$1',[digest(raw)]);res.setHeader('Set-Cookie','dge_session=; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=0');return res.json({ok:true})}const u=await authenticate(req);return res.json(await action(d.acao,d,u))}catch(e){const known=/inválid|inválida|não encontrad|Sem permissão|expirada|insuficiente|maior que|Confira|Preencha|Informe|existe|grande|imimplementada/i.test(e.message);if(!known)console.error(e);return res.status(known?400:500).json({ok:false,erro:known?e.message:'Falha no servidor. Confira a configuração e os logs da Vercel.'})}}
